name: daily

on:
  # GitHub Actions = UTC. On programme 2 crons pour couvrir été/hiver.
  schedule:
    - cron: '59 21 * * *'  # 23:59 Europe/Paris quand CEST (été, UTC+2)
    - cron: '59 22 * * *'  # 23:59 Europe/Paris quand CET  (hiver, UTC+1)
  workflow_dispatch: {}     # lancer manuellement si besoin

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}

      # (Optionnel) Cache des modèles HF si tu utilises mT5 en prod.
      # Décommente si tu veux lancer HuggingFace sur le runner.
      # - name: Cache HF models
      #   uses: actions/cache@v4
      #   with:
      #     path: hf_cache
      #     key: hf-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- CHOIX 1 (recommandé pour GitHub): léger et fiable (pas de gros DL) ---
      - name: Run script (today, Paris, LexRank)
        run: |
          python main.py --summarizer lexrank

      # --- CHOIX 2 (si tu veux absolument mT5 sur GitHub) ---
      # Décommente ce bloc et commente le bloc LexRank au-dessus.
      # - name: Run script (today, Paris, mT5 small)
      #   env:
      #     HUGGINGFACE_HUB_CACHE: ${{ github.workspace }}/hf_cache
      #   run: |
      #     python main.py --summarizer hf --hf-model csebuetnlp/mT5_small_m2o_xlsum --points 6

      - name: Commit & push results
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: daily summaries" || echo "no changes"
          git push

